CREATE TABLE Inventory (
	ITEM_ID INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ITEM_NAME VARCHAR(100),
	ITEM_CATEGORY VARCHAR(50),
	ITEM_TYPE VARCHAR(50),
	ITEM_DESCRIPTION VARCHAR(255),
	ITEM_CONDITION VARCHAR(50),
	ITEM_ASKING_PRICE DECIMAL(18, 2),
	ITEM_PURCHASE_PRICE DECIMAL(18, 2),
	ITEM_TIMESTAMP DATE,
)
CREATE TABLE Sold (
	ITEM_ID INTEGER NOT NULL PRIMARY KEY,
	ITEM_NAME VARCHAR(255),
	ITEM_CATEGORY VARCHAR(255),
	ITEM_TYPE VARCHAR(255),
	ITEM_DESCRIPTION VARCHAR(255),
	ITEM_CONDITION VARCHAR(50),
	ITEM_PURCHASE_PRICE DECIMAL(18, 2),
	ITEM_SELLING_PRICE DECIMAL(18, 2),
	ITEM_TIMESTAMP DATE
)
